apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argo
  labels:
    app: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/masem/kube-test.git
    targetRevision: HEAD
    path: argo/cd
  destination:
    name: in-cluster
    namespace: argo
  syncPolicy:
    syncOptions:
    - Validate=true
    - CreateNamespace=true

