apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kad-test
  namespace: argo
spec:
  destination:
    namespace: kad-test
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm
    repoURL: https://github.com/masem/kube-test.git
    targetRevision: HEAD
#    path: argo/cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

